name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 18.223.158.194 >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Test SSH connection
        run: |
          ssh ubuntu@18.223.158.194 "cd /home/ubuntu/nodeprojects/nodebaseprojects &&   sudo git pull origin main"

