name: Pull on Push

on:
  push:
    branches:
      - main  # Reemplaza con el nombre de tu rama principal si es diferente

jobs:
  pull:
    runs-on: ubuntu-latest  # Puedes cambiar el sistema operativo si es necesario

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pull Changes on Computer B
        run: |
          ssh ubuntu@ec2-18-223-158-194.us-east-2.compute.amazonaws.com "cd /home/ubuntu/nodeprojects/nodebaseprojects &&   git pull origin main"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
